# Site settings
title: Katrina Wehr, Ph.D.
email: katrina.m.wehr@gmail.com
description: Thoughts on design, research, and learning
baseurl: "https://kat-wehr.github.io/drkatwehr-blog" # Leave empty if using username.github.io, or "/blog" if subdirectory
url: "https://kat-wehr.github.io/drkatwehr-blog" # Change to your actual URL

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
